# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 11f20360218d1a2c97e877630198fc1080858dbea9cc52834cee82908f0b7ba3878c68dd18a3305df834a8d899cbcffa75af2730d76b1d99ce82d737e0dbcd7f

test:
  secret_key_base: f07629022422eca892305382f1e3ea08e0eeb1b3fc3c222ed6605f69d48d911fe5542d76d0b7a88218527b24ca6b051d7e656411d91549c6cc470e85c16bfff8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
